name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'inventario_app/backend-python/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'inventario_app/backend-python/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./inventario_app/backend-python

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        # Asegúrate de que pytest esté en tu requirements.txt
        pip install -r requirements.txt
        
    - name: Ejecutar pruebas
      run: pytest
