version: '3.8'
services:
  backend:
    build: ./inventario_app/backend-python
    ports:
      - "5000:5000"
    volumes:
      - ./inventario_app/backend-python:/app
    depends_on:
      - frontend

  frontend:
    build: ./inventario_app/frontend-react
    ports:
      - "3000:80"
